name: tests

on: [pull_request]

jobs:
  generate-xcode-proj:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate Xcode project
      run: swift package generate-xcodeproj -v
    
  codecov:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate coverage report
      run: 
      - xcodebuild -scheme AsyncImageFetcher -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 Pro' -enableCodeCoverage YES build test
      - sh swift-package-coverage.sh .
    - name: Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        token: 638fc865-67b1-41c3-93fb-9f4f955eb9bf
        # file: 
